import warnings

insert_alpha = {
    "bbsi_1": "GAAGAC",
    "2nt_spacer_1": "TG",
    "cysteine_overhang": "CTGT",  # preceding base and TGT (cysteine)
    "mu_trac_patial_overhang": "ATCCA",  # preceding base (from J) and TCCA
    "2nt_spacer_2": "TA",
    "bbsi_2": "GTCTTC",
}

# TGTG and CC (normal) or TGTA and GC (alternative, for V 20-1 and 29-1)
alt_v_genes_beta = ["TRBV20-1", "TRBV29-1"]

insert_beta = {
    "bbsi_1": "GAAGAC",
    "2nt_spacer_1": "GT",
    "cysteine_overhang": "TGTG",  # preceding base and TGT (cysteine)
    "cysteine_overhang_alt": "TGTA",  # preceding base and TGA (cysteine) ALT
    "complete_a_or_s_codon": "CC",  # 2nt to complete A or S codon
    "complete_a_or_s_codon_alt": "GC",  # 2nt to complete A or S codon ALT
    "last_codon_j": "GAG",  # force last codon to be GAG (GAA also codes for Glu, but does not match GAGG overhang)
    "4th_nt_overhang": "G",  # 4th nt over GAGG overhang
    "2nt_spacer_2": "TC",
    "bbsi_2": "GTCTTC",
}

# checks forwards and backwards
sites_to_check = {
    # 'kozak1': 'CCACC',
    "kozak2": "GCCACC",  # only need this one if we also add RT
    # 'kozak3': 'GGTGG',
    # 'kozak4': 'GGTGGC',
    "repeat5": "GGGGGG",  # only need this one if we also add RT
    # 'repeat6': 'CCCCCC',
    "repeat7": "TTTTTT",  # only need this one if we also add RT
    # 'repeat8': 'AAAAAA',
    "repeat9": "GGGGG",
    # 'repeat10': 'CCCCC',
    "repeat11": "TTTTT",
    # 'repeat12': 'AAAAA',
    "TRBV7-2_mispriming": "GGTGTGAC",  # is subset of RT_muTCRb_1_b1_priming
    "RT_muTCRb_1_b1_priming": "TTTTGGAGGTGTGACG",
    "RT_muTCRb_1_b1_extension": "CTACACGACGCTCTTCCGATCTAAGACCTAC",
    "P20_PCR_handle": "TGAGCACGTCACACCTCCAAAAACACTGA",
    "plate_P20_IL2SP_Fw_1_priming": "AGCTGCTGAGCTGCATCG",
    "plate_P20_IL2SP_Fw_2_priming": "ACCATGTACAGAATGCAGCT",
    "plate_P20_Pep_Fw_5_priming": "TCTGTTCTGTTACACAAGGGAAGAAA",
    "plate_cDNA_TCRb_R2_Fw_priming": "GTGGACCATCCTCTAGACTG",
    "plate_cDNA_TruSeqR2_1_priming": "CTACACGACGCTCTTCCGATCT",
    "plate_cDNA_Fw_common_extension": "GGAGTTCAGACGTGTGCTCTTCCGATCT",
    "Prep-I_Fw_priming": "ATGGAGGAGAACCCTGGACCTACAAGC",
    "Prep-II_Fw_priming": "ACCTGCGGATGAAGCTGCCCG",
    "Prep-Fw_extension": "CAAGCAGAAGACGGCATACG",
    "Prep_Rv_priming": "AATGATACGGCGACCACCGAGATCT",
    "P7": "CAAGCAGAAGACGGCATACGAGAT",
    "P5": "GTGTAGATCTCGGTGGTCGCCGTATCATT",
    "TruSeqR1": "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "TruSeqR2": "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT",
    # ZVM
    "pMX_TCRlib_TCRb_fw_priming": "GGGGTGGACCATCCTCTAGACTGC",
    "Lenti/pMX_TCRlib_TCRa_fw_priming": "GCTGGCGACGTGGAGGAGAACC",
    # CRR
    "P5 (CRR)": "AATGATACGGCGACCACCGA",
    "pMX_bindingsite_rev1": "GGGACACTTTTGGAGGTGTGACGTTCC",
    "pMX_bindingsite_fwd_1": "GGGGTGGACCATCCTCTAGACTGC",
    "pcr_v1_MCSV_mg_fwd_3": "GGACCTGATCAGCAACAACGAGC",
    "seq_CD74_fwd_1": "GACAAGCTGACCGTGACCAGCC",
    "pcr_v1_MCSV_rev_1": "GATCCGACTCGGTGCCACTTTTTCAAC",
}

#
# AATGATACGGCGACCACCGA - Illumina_P5                   # not same as mari
# CAAGCAGAAGACGGCATACGAGAT - Illumina_P7

# GGGACACTTTTGGAGGTGTGACGTTCC - pMX_bindingsite_rev1   # not same size as fwd
# GGGGTGGACCATCCTCTAGACTGC - pMX_bindingsite_fwd_1

# GGACCTGATCAGCAACAACGAGC - pcr_v1_MCSV_mg_fwd_3       #
# GACAAGCTGACCGTGACCAGCC - seq_CD74_fwd_1
# GATCCGACTCGGTGCCACTTTTTCAAC - pcr_v1_MCSV_rev_1

# J gene Residue 119 + rest + orphan residue
j_gene_res119_rest_orphan_dict_alpha = {
    "TRAJ1": "GKGTRVSTSPH",
    "TRAJ10": "GTGTQLKVELN",
    "TRAJ11": "GKGTMLLVSPD",
    "TRAJ12": "GSGTRLLVRPD",
    "TRAJ13": "GIGTKLQVIPN",
    "TRAJ14": "GSGTRLSVKPD",
    "TRAJ15": "GKGTTLSVSSN",
    "TRAJ16": "ARGTMLKVDLN",
    "TRAJ17": "GGGTRVLVKPN",
    "TRAJ18": "GRGTQLTVWPD",
    "TRAJ19": "GKGSKHNVTPN",
    "TRAJ2": "GKGTHVFIISD",
    "TRAJ20": "GAGTTVTVRAN",
    "TRAJ21": "GSGTKLNVKPN",
    "TRAJ22": "GSGTQLTVLPD",
    "TRAJ23": "GQGTELSVKPN",
    "TRAJ24": "GAGTQVVVTPD",
    "TRAJ25": "GKGTRLLVKPN",
    "TRAJ26": "GPGTRLSVLPY",
    "TRAJ27": "GDGTTLTVKPN",
    "TRAJ28": "GKGTKLSVIPN",
    "TRAJ29": "GKGTRLSVIAN",
    "TRAJ3": "GSGTRLSIRPN",
    "TRAJ30": "GKGTRLHILPN",
    "TRAJ31": "GDGTQLVVKPN",
    "TRAJ32": "GTGTLLAVQPN",
    "TRAJ33": "GAGTKLIIKPD",
    "TRAJ34": "GTGTRLQVFPN",
    "TRAJ35": "GSGTQVIVLPH",
    "TRAJ36": "GTGTRLTVIPY",
    "TRAJ37": "GQGTTLQVKPD",
    "TRAJ38": "GLGTSLAVNPN",
    "TRAJ39": "GGGTRLMVKPH",
    "TRAJ4": "GAGTRLAVHPY",
    "TRAJ40": "GTGTRLKVLAN",
    "TRAJ41": "GKGTSLLVTPH",
    "TRAJ42": "GKGTKLSVKPN",
    "TRAJ43": "GAGTRLTVKPN",
    "TRAJ44": "GTGTRLQVTLD",
    "TRAJ45": "GKGTHLIIQPY",
    "TRAJ46": "GTGTRLAVRPN",
    "TRAJ47": "GAGTILRVKSY",
    "TRAJ48": "GTGTRLTIIPN",
    "TRAJ49": "GTGTSLTVIPN",
    "TRAJ5": "GSGTRLQVQPN",
    "TRAJ50": "GPGTSLSVIPN",
    "TRAJ52": "GQGTILTVHPN",
    "TRAJ53": "GKGTLLTVNPN",
    "TRAJ54": "GQGTRLTINPN",
    "TRAJ56": "GKGITLSVRPD",
    "TRAJ57": "GKGTKLTVNPY",
    "TRAJ58": "GEGTQLTVNPD",
    "TRAJ59": "GMGTQVRVKLY",
    "TRAJ6": "GRGTSLIVHPY",
    "TRAJ7": "GKGNQVVVIPN",
    "TRAJ8": "GTGTRLLVSPN",
    "TRAJ9": "GAGTRLFVKAN",
}

j_gene_res119_rest_orphan_dict_beta = {
    "TRBJ1-1": "GQGTRLTVVE",
    "TRBJ1-2": "GSGTRLTVVE",
    "TRBJ1-3": "GEGSWLTVVE",
    "TRBJ1-4": "GSGTQLSVLE",
    "TRBJ1-5": "GDGTRLSILE",
    "TRBJ1-6": "GNGTRLTVTE",
    "TRBJ2-1": "GPGTRLTVLE",
    "TRBJ2-2": "GEGSRLTVLE",
    "TRBJ2-3": "GPGTRLTVLE",
    "TRBJ2-4": "GAGTRLSVLE",
    "TRBJ2-5": "GPGTRLLVLE",
    "TRBJ2-6": "GAGSRLTVLE",
    "TRBJ2-7": "GPGTRLTVTE",
}


plate_pool_primers_fw = [
    "GTATGTCGGCTCTCGTATCG",  # Ag_pool_Fw_1
    "AAGGCGCTCGGATAATACTC",  # Ag_pool_Fw_2
    "AGCTCAATCTAACAGTGGGG",  # Ag_pool_Fw_3
    "AAGACGATCCGAGCCATTAC",  # Ag_pool_Fw_4
    "ATCCAGGAGGTCTAGGAACC",  # Ag_pool_Fw_5
    "ATCCTAGAAAAGGCGAAGGC",  # Ag_pool_Fw_6
    #'AGCATCCGTCTAAATCTCGG',# For plates we can have the same orthoprimer occurring multiple times across combinations, but not for oligo subpools...
    "AATGCAAAGCTATTAGCGCG",  # Ag_pool_Fw_7
    "ATTAGTACACTCCGTGAGCG",  # Ag_pool_Fw_8
    "AGATTAGCCGACTTTCCTGG",  # Ag_pool_Fw_9
    #'AGATTAGCCGACTTTCCTGG',
    #'ATGCTAGCTGGAACTATCGG',
    #'AAGGCGCTCGGATAATACTC',
    #'AGACACAAGGCTGATTCCAG', # From here onwards, primers overlap with final standardized ortho_primer_combinations. That is why these primers are commented.
    #'AATGCGTCATTTTACACGGC',
    #'ATTCAAGGGTTGGACGACTC',
    #'AATATCACGCAAAAGCACCG',
    #'AGACAAGCCTTAACCGTAGG',
    #'ATCCTAGAAAAGGCGAAGGC',
    #'AAGGAACTATGGCATCGAGC'
]


# I only kept this list here because it is important for the epitope variant pools that contain subpools that already use these rev primers
# I added a deprecation warning below to warn if users import the list.
plate_pool_primers_rv = [
    "GTAGGTTCGTGCTCCTTTGA",  # Ag_pool_Rev_1
    "CATCCTTATGCGATACGGGT",  # Ag_pool_Rev_2
    "GTACGTCTGAACTTGGGACT",  # Ag_pool_Rev_3
    "GGTTACAATAAGGGCTCCGT",  # Ag_pool_Rev_4
    "CTTGAAATCTTGTCGCACGG",  # Ag_pool_Rev_5
    "GGCTACCTAAGTTCGATCCG",  # Ag_pool_Rev_6
    #'GTACGTCTGAACTTGGGACT', # For plates we can have the same orthoprimer occurring multiple times across combinations, but not for oligo subpools...
    "CCTGTTCTGGTATGCGATGT",  # Ag_pool_Rev_7
    "GGCACTCATTGGGACTTTTC",  # Ag_pool_Rev_8
    "GGGTTTAGTCCGGCAATACT",  # Ag_pool_Rev_9
    #'GTGTCACATTGTGTCGGACT',
    #'GGCTACCTAAGTTCGATCCG',
    #'GGGCACTCAATATACCCTGT',
    #'GGACCTTGACGCCTAATACT', # From here onwards, primers overlap with final standardized ortho_primer_combinations. That is why these primers are commented.
    #'GCGTATACCTTGCTTCCTGT',
    #'CTGGCCTGTCAACTTTATGC',
    #'GGGTGCCTTGCTAATCTAGT',
    #'GTGTCACATTGTGTCGGACT',
    #'CGATAAGTAGCCCCTAGCAG',
    #'GGCTCGATACAGTTTCACGT'
]


# Fw primer is first primer in list & rv primer second primer in list:
# Rv primers need to be added as their reverse_complement to the oligos
plate_primers_dict = dict(zip(range(0, len(plate_pool_primers_fw)), [[plate_fw, plate_rv] for plate_fw, plate_rv in zip(plate_pool_primers_fw, plate_pool_primers_rv)]))

warnings.warn(
    "Both plate_pool_primers_fw and plate_pool_primers_rv lists are deprecated (only use these lists for the epitope variant pools!).For TCR assembly, use plate_pool_primers_df instead!",
    DeprecationWarning,
    stacklevel=2,
)


# The trimmed_beta_model_tcr_dict is used by the generate_assembly_nt_refs function in reference.py.
# It is called "trimmed" because we always align plate-base seq data against trimmed TCRs.
# trimmed_beta_model_tcr_dict = {
#    'DMF4':'CAGGATGCTCAGCCGTGTTCCATCCCCAAAGTGCTGTGGCTGCCCCACTCCGACTTCGCTGATAGCACAGAAGTACACAGATGTCTGGGAGCTTGTAGCGCTTTC',
#    'DMF5':'CACCACAGTCAGTCTGGTTCCCTGTCCAAAGAAGGCCTCGGTGCCGAAGCTCAGGCTGGATGCGCAAAAATAGACGCTAGTTTGGCTAGGGACTGCGCTGGCCAG',
#    '1G4':'CAGCACGGTCAGTCTGGATCCTTCTCCAAAGAACAGTTCCCCAGTATTGCCGACATAGCTGGATGCGCAAAAATAGACGGAAGTCTGGGAGGGTGCAGCGCTCAG'
# }

trimmed_beta_model_tcr_dict = {
    "DMF4": "GAAAGCGCTACAAGCTCCCAGACATCTGTGTACTTCTGTGCTATCAGCGAAGTCGGAGTGGGGCAGCCACAGCACTTTGGGGATGGAACACGGCTGAGCATCCTG",
    "DMF5": "CTGGCCAGCGCAGTCCCTAGCCAAACTAGCGTCTATTTTTGCGCATCCAGCCTGAGCTTCGGCACCGAGGCCTTCTTTGGACAGGGAACCAGACTGACTGTGGTG",
    "1G4": "CTGAGCGCTGCACCCTCCCAGACTTCCGTCTATTTTTGCGCATCCAGCTATGTCGGCAATACTGGGGAACTGTTCTTTGGAGAAGGATCCAGACTGACCGTGCTG",
    "CDK4_53": "TGTCCACCCTGAAGATCCAGCGGACCCAGCAGGAAGATAGCGCCGTCTATCTGTGCGCCAGCAGCCAGAACTACGAGCAGTACTTCGGCCCTGGCACCCGGCTGACCGTGACC",
}

# model_epitope_dict = {
#     'p20_stuffer': 'AGAGACGTCCCGCTGATTCGCTATAACAGCGTGTAG',
#     'YLQ': 'CAGCAGGAAGGTTCTAGGCTGCAGGTAGCTGTTGGT',
#     'CDK4mut': 'CACGAAGTGGCCGCTGTGGGGGTCCAGGGCGCTGTTGGT',
#     'GNL3L': 'CACGGGCACGCTGCAGCAGTTCAGGTTGCTGTTGGT',
#     'GLC': 'CAGCATGGCCACCAGGGTGCACAGGCCGCTGTTGGT',
#     'JM22': 'CAGGGTGAACACGAAGCCCAGGATGCCGCTGTTGGT',
#     'KLW': 'CAGCTGCACGCACTGAGCCCACAGCTTGCTGTTGGT',
#     'LLY': 'CAGGAAGTAGTTGGCGTCGTACAGCAGGCTGTTGGT',
#     'NLV': 'CACGGTGGCCACCATGGGCACCAGGTTGCTGTTGGT',
#     'NYESO1': 'GGCTTGGGTGATCCACATCAGCAGGCTGCTGTTGGT',
#     'SL9': 'CAGGGTGGCCACGGTGTTGTACAGGCTGCTGTTGGT',
#     'Tax': 'CACGTACACGGGGTAGCCGAACAGCAGGCTGTTGGT',
#     'MART1-ELA': 'CACGGTCAGGATGCCGATGCCGGCCAGCTCGCTGTTGGT'
# }

model_epitope_dict = {
    "p20_stuffer": "CTACACGCTGTTATAGCGAATCAGCGGGACGTCTCT",
    "YLQ": "ACCAACAGCTACCTGCAGCCTAGAACCTTCCTGCTG",
    "CDK4mut": "ACCAACAGCGCCCTGGACCCCCACAGCGGCCACTTCGTG",
    "GNL3L": "ACCAACAGCAACCTGAACTGCTGCAGCGTGCCCGTG",
    "GLC": "ACCAACAGCGGCCTGTGCACCCTGGTGGCCATGCTG",
    "JM22": "ACCAACAGCGGCATCCTGGGCTTCGTGTTCACCCTG",
    "KLW": "ACCAACAGCAAGCTGTGGGCTCAGTGCGTGCAGCTG",
    "LLY": "ACCAACAGCCTGCTGTACGACGCCAACTACTTCCTG",
    "NLV": "ACCAACAGCAACCTGGTGCCCATGGTGGCCACCGTG",
    "NYESO1": "ACCAACAGCAGCCTGCTGATGTGGATCACCCAAGCC",
    "SL9": "ACCAACAGCAGCCTGTACAACACCGTGGCCACCCTG",
    "Tax": "ACCAACAGCCTGCTGTTCGGCTACCCCGTGTACGTG",
    "MART1-ELA": "ACCAACAGCGAGCTGGCCGGCATCGGCATCCTGACCGTG",
}

tcr_golden_gate_constant_nt_seq_dict = {
    "muTRBC_P2A_nt": "GACCTGCGGAACGTCACACCTCCAAAAGTGTCCCTCTTCGAGCCAAGCAAAGCAGAGATCGCAAACAAGCAGAAAGCTACACTGGTGTGTCTCGCTAGAGGCTTTTTTCCCGACCATGTGGAGCTGTCCTGGTGGGTGAATGGAAAGGAGGTGCACAGCGGAGTGTGTACCGATCCACAGGCCTACAAGGAGAGCAACTATAGCTACTGTCTGAGCTCCAGACTGCGGGTCAGCGCAACTTTTTGGCACAACCCTCGGAACCATTTTAGATGCCAGGTGCAGTTTCATGGCCTGTCCGAAGAAGATAAGTGGCCAGAGGGAAGCCCAAAGCCAGTCACTCAAAACATCTCCGCCGAAGCTTGGGGAAGGGCCGATTGCGGGATCACAAGCGCTTCCTATCATCAGGGCGTGCTGTCCGCCACAATCCTGTACGAAATCCTGCTCGGCAAAGCTACCCTGTATGCTGTCCTGGTCAGCGGACTCGTGCTGATGGCCATGGTGAAGAAGAAGAACAGCGGCAGCGGAGCCACCAACTTTTCCCTGCTGAAGCAAGCTGGCGACGTGGAGGAGAACCCAGGGCCC"
}


snapgene_feature_dict = {
    "mTRAC": "TCCAGAACCCCGAGCCCGCCGTATACCAGCTGAAGGACCCCCGATCTCAGGATAGTACTCTGTGCCTGTTCACCGACTTTGATAGTCAGATCAATGTGCCTAAAACCATGGAATCCGGAACTTTTATTACCGACAAGTGCGTGCTGGATATGAAAGCCATGGACAGTAAGTCAAACGGCGCCATCGCTTGGAGCAATCAGACATCCTTCACTTGCCAGGATATCTTCAAGGAGACCAACGCAACATACCCATCCTCTGACGTGCCCTGTGATGCCACCCTGACAGAGAAGTCTTTCGAAACAGACATGAACCTGAATTTTCAGAATCTGAGCGTGATGGGCCTGAGAATCCTGCTGCTGAAGGTCGCTGGGTTTAATCTGCTGATGACACTGCGGCTGTGGTCCTCA",
    "T2A": "GGATCTGGCGAGGGCAGAGGATCTCTGCTGACCTGCGGAGATGTGGAAGAGAACCCTGGCCCC",
    "puro": "ATGACCGAGTACAAGCCCACCGTGCGGCTGGCCACAAGAGATGATGTGCCTAGAGCTGTGCGGACACTGGCCGCTGCCTTTGCCGATTATCCTGCCACCAGACACACAGTGGACCCCGACAGACACATCGAGAGAGTGACCGAGCTGCAAGAGCTGTTCCTGACCAGAGTCGGCCTGGACATCGGAAAAGTGTGGGTCGCAGATGATGGCGCCGCTGTGGCTGTTTGGACAACACCTGAGTCTGTGGAAGCCGGCGCTGTGTTTGCCGAGATCGGACCTAGAATGGCCGAGCTGTCTGGCTCTAGACTGGCTGCTCAGCAGCAGATGGAAGGACTGCTGGCCCCTCACAGACCTAAAGAGCCTGCCTGGTTTCTGGCCACCGTGGGAGTGTCTCCAGACCACCAAGGCAAAGGACTGGGATCTGCTGTGGTGCTGCCTGGCGTTGAAGCCGCTGAAAGAGCTGGCGTTCCCGCCTTCCTGGAAACAAGCGCCCCTAGAAACCTGCCTTTCTACGAGAGACTGGGCTTCACCGTGACCGCCGATGTGGAAGTTCCTGAGGGCCCTAGAACCTGGTGCATGACCAGAAAGCCTGGCGCCTAA",
    "NeoR/KanR": "TCAGAAGAACTCGTCAAGAAggcgatagaaggcgatgcgctgcgaatcgggagcggcgataccgtaaagcacgaggaagcggtcagcccattcgccgccaagctcttcagcaatatcacgggtagccaacgctatgtcctgatagcggtccgccacacccagccggccacagtcgatgaatccagaaaagcggccattttccaccatgatattcggcaagcaggcatcgccatgggtcacgacgagatcctcgccgtcgggcatgctcgccttgagcctggcgaacagttcggctggcgcgagcccctgatgctcttcgtccagatcatcctgatcgacaagaccggcttccatccgagtacgtgctcgctcgatgcgatgtttcgcttggtggtcgaatgggcaggtagccggatcaagcgtatgcagccgccgcattgcatcagccatgatggatactttctcggcaggagcaaggtgagatgacaggagatcctgccccggcacttcgcccaatagcagccagtcccttcccgcttcagtgacaacgtcgagcacagctgcgcaaggaacgcccgtcgtggccagccacgatagccgcgctgcctcgtcttgcagttcattcagggcaccggacaggtcggtcttgacaaaaagaaccgggcgcccctgcgctgacagccggaacacggcggcatcagagcagccgattgtctgttgtgcccagtcatagccgaatagcctctccacccaagcggccggagaacctgcgtgcaaTCCATCTTGTTCAATCAT",
    "gag (truncated)": "GGCCAGACTGTTACCACTCCCTTAAGTTTGACCTTAGGTCACTGGAAAGATGTCGAGCGGATCGCTCACAACCAGTCGGTAGATGTCAAGAAGAGACGTTGGGTTACCTTCTGCTCTGCAGAATGGCCAACCTTTAACGTCGGATGGCCGCGAGACGGCACCTTTAACCGAGACCTCATCACCCAGGTTAAGATCAAGGTCTTTTCACCTGGCCCGCATGGACACCCAGACCAGGTCCCCTACATCGTGACCTGGGAAGCCTTGGCTTTTGACCCCCCTCCCTGGGTCAAGCCCTTTGTACACCCTAAGCCTCCGCCTCCTCTTCCTCCATCCGCCCCGTCTCTCCCCCTTGAACCTCCTCGTTCGACCCCGCCTCGATCCTCCCTTTATCCAGCCCTCACTCCTTCTCTAGGCGCC",
    "mTRBC": "GAGGACCTGCGGAACGTCACACCTCCAAAAGTGTCCCTCTTCGAGCCAAGCAAAGCAGAGATCGCAAACAAGCAGAAAGCTACACTGGTGTGTCTCGCTAGAGGCTTTTTTCCCGACCATGTGGAGCTGTCCTGGTGGGTGAATGGAAAGGAGGTGCACAGCGGAGTGTGTACCGATCCACAGGCCTACAAGGAGAGCAACTATAGCTACTGTCTGAGCTCCAGACTGCGGGTCAGCGCAACTTTTTGGCACAACCCTCGGAACCATTTTAGATGCCAGGTGCAGTTTCATGGCCTGTCCGAAGAAGATAAGTGGCCAGAGGGAAGCCCAAAGCCAGTCACTCAAAACATCTCCGCCGAAGCTTGGGGAAGGGCCGATTGCGGGATCACAAGCGCTTCCTATCATCAGGGCGTGCTGTCCGCCACAATCCTGTACGAAATCCTGCTCGGCAAAGCTACCCTGTATGCTGTCCTGGTCAGCGGACTCGTGCTGATGGCCATGGTGAAGAAGAAGAACAGCGGCAGCGGAGCCACCAACTTTTCCCTGCTGAAGCAAGCTGGCGACGT",
    "LTR": "AATGAAAGACCCCACCTGTAGGTTTGGCAAGCTAGCTTAAGTAACGCCATTTTGCAAGGCATGGAAAAATACATAACTGAGAATAGAAAAGTTCAGATCAAGGTCAGGAACAGATGGAACAGCTGAATATGGGCCAAACAGGATATCTGTGGTAAGCAGTTCCTGCCCCGGCTCAGGGCCAAGAACAGATGGAACAGCTGAATATGGGCCAAACAGGATATCTGTGGTAAGCAGTTCCTGCCCCGGCTCAGGGCCAAGAACAGATGGTCCCCAGATGCGGTCCAGCCCTCAGCAGTTTCTAGAGAACCATCAGATGTTTCCAGGGTGCCCCAAGGACCTGAAATGACCCTGTGCCTTATTTGAACTAACCAATCAGTTCGCTTCTCGCTTCTGTTCGCGCGCTTCTGCTCCCCGAGCTCAATAAAAGAGCCCACAACCCCTCACTCGGCGCGCCAGTCCTCCGATTGACTGAGTCGCCCGGGTACCCGTGTATCCAATAAACCCTCTTGCAGTTGCATCCGACTTGTGGTCTCGCTGTTCCTTGGGAGGGTCTCCTCTGAGTGATTGACTACCCGTCAGCGGGGGTCTTTCATT",
}
